# Generated by Django 3.2.11 on 2022-02-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='sid',
            new_name='eid',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='sname',
            new_name='ename',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='ssal',
            new_name='esal',
        ),
    ]
