# Generated by Django 3.2.11 on 2022-02-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp3', '0002_auto_20220202_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emp',
            new_name='Employee',
        ),
    ]
